easytravel-mongodb:
  hostname: easytravel-mongodb
  image: "dynatrace/easytravel-mongodb"
  ports:
  - 27017
  - 28017

easytravel-backend:
  hostname: easytravel-backend
  image: "dynatrace/easytravel-backend"
  ports:
  - 8080
  environment:
    CATALINA_OPTS: "-Dconfig.apmServerDefault=${ET_APM_SERVER_DEFAULT} -Xmx300m"
    ET_DATABASE_LOCATION: "easytravel-mongodb:27017"

easytravel-frontend:
  hostname: easytravel-frontend
  image: "dynatrace/easytravel-frontend"
  ports:
  - 8080
  environment:
    CATALINA_OPTS: "-Dconfig.apmServerDefault=${ET_APM_SERVER_DEFAULT} -Xmx525m"
    ET_BACKEND_URL: "http://easytravel-backend:8080"
  labels:
    kompose.service.expose: "easytravel-frontend"
    kompose.service.type: nodeport

easytravel-www:
  hostname: easytravel-www
  image: "dynatrace/easytravel-nginx"
  ports:
  - 80
  - 8080
  environment:
    ET_FRONTEND_LOCATION: "easytravel-frontend:8080"
    ET_BACKEND_LOCATION: "easytravel-backend:8080"

loadgen:
  image: "dynatrace/easytravel-loadgen"
  environment:
    ET_APM_SERVER_DEFAULT: "${ET_APM_SERVER_DEFAULT}"
    ET_FRONTEND_URL: "http://easytravel-www:80"
    ET_BACKEND_URL: "http://easytravel-www:8080"
    ET_PROBLEMS: "BadCacheSynchronization,CPULoad,DatabaseCleanup,DatabaseSlowdown,FetchSizeTooSmall,JourneySearchError404,JourneySearchError500,LoginProblems,MobileErrors,TravellersOptionBox"
